name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        isabelle-version: [2024]
        #os: [ubuntu-22.04, ubuntu-latest]
        #isabelle-version: [2022, 2023, 2024]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Isabelle
        uses: ./
        with: 
          isabelle-version: ${{matrix.isabelle-version}}
      - name: Check Isabelle version
        shell: bash
        run: |
          isabelle version
          if [[ "$(isabelle version)" == "Isabelle${{matrix.isabelle-version}}" ]]; then
            echo "Success"
            exit 0
          else
            echo "Incorrect Isabelle version"
            exit 1
          fi